# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clightx.proto\"\x07\n\x05\x45mpty\"\x1a\n\x0cSuccessReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x17\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x41\n\x06Lightx\x12\x1f\n\x04Ping\x12\x06.Empty\x1a\r.SuccessReply\"\x00\x12\x16\n\x04\x45xit\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lightx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=16
  _EMPTY._serialized_end=23
  _SUCCESSREPLY._serialized_start=25
  _SUCCESSREPLY._serialized_end=51
  _PINGREPLY._serialized_start=53
  _PINGREPLY._serialized_end=76
  _LIGHTX._serialized_start=78
  _LIGHTX._serialized_end=143
# @@protoc_insertion_point(module_scope)
