# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x65px.proto\"\x07\n\x05\x45mpty\"\x1a\n\x0cSuccessReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x17\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x8c\x01\n\x0cInferRequest\x12\x13\n\x0bimage_index\x18\x01 \x01(\x05\x12\x12\n\nmask_index\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x11\n\tcamera_id\x18\x04 \x01(\t\x12\x16\n\x0e\x63\x61pture_config\x18\x05 \x01(\t\x12\x15\n\rcapture_index\x18\x06 \x01(\x05\x32g\n\x05\x44\x65\x65px\x12\x1f\n\x04Ping\x12\x06.Empty\x1a\r.SuccessReply\"\x00\x12%\n\x05Infer\x12\r.InferRequest\x1a\r.SuccessReply\x12\x16\n\x04\x45xit\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=15
  _EMPTY._serialized_end=22
  _SUCCESSREPLY._serialized_start=24
  _SUCCESSREPLY._serialized_end=50
  _PINGREPLY._serialized_start=52
  _PINGREPLY._serialized_end=75
  _INFERREQUEST._serialized_start=78
  _INFERREQUEST._serialized_end=218
  _DEEPX._serialized_start=220
  _DEEPX._serialized_end=323
# @@protoc_insertion_point(module_scope)
