batch_size: 4
epochs: 10
root: optic_disc_seg

train_dataset:
  type: SegDataset
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_factor: 0.5
      max_factor: 2.0
      scale_step: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Resize
      target_size: [512, 512]
    - type: Normalize

valid_dataset:
  type: SegDataset
  mode: valid
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize

optimizer:
  type: adam
  # momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  num_classes: 2
  backbone:
    type: STDC2
    in_channels: 3
    pretrained: PP_STDCNet2
