# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimagex.proto\"\x07\n\x05\x45mpty\"\x1a\n\x0cSuccessReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x17\n\tPingReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xea\x01\n\x11InferReadyRequest\x12\x13\n\x0bimage_index\x18\x01 \x01(\x05\x12\x12\n\nmask_index\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x11\n\tcamera_id\x18\x04 \x01(\t\x12\x16\n\x0e\x63\x61pture_config\x18\x05 \x01(\t\x12\x15\n\rcapture_index\x18\x06 \x01(\x05\x12\x17\n\x0finfer_timestamp\x18\x07 \x01(\x05\x12\x0f\n\x07network\x18\x08 \x01(\t\x12\n\n\x02ok\x18\t \x01(\x08\x12\x10\n\x08ng_stats\x18\n \x01(\t\x12\x0f\n\x07results\x18\x0b \x01(\t2r\n\x06Imagex\x12\x1f\n\x04Ping\x12\x06.Empty\x1a\r.SuccessReply\"\x00\x12/\n\nInferReady\x12\x12.InferReadyRequest\x1a\r.SuccessReply\x12\x16\n\x04\x45xit\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagex_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=16
  _EMPTY._serialized_end=23
  _SUCCESSREPLY._serialized_start=25
  _SUCCESSREPLY._serialized_end=51
  _PINGREPLY._serialized_start=53
  _PINGREPLY._serialized_end=76
  _INFERREADYREQUEST._serialized_start=79
  _INFERREADYREQUEST._serialized_end=313
  _IMAGEX._serialized_start=315
  _IMAGEX._serialized_end=429
# @@protoc_insertion_point(module_scope)
